In [1]:
from xml.etree import ElementTree

In [3]:
tree = ElementTree.parse("rss.xml")

In [4]:
root = tree.getroot()

In [5]:
import pandas as pd

In [9]:
dfList = []
for item in root.findall("channel/item/description/body/location/data"):
    tmEf = item.find("tmEf").text
    tmn = item.find("tmn").text
    tmx = item.find("tmx").text
    wf = item.find("wf").text
    df = pd.DataFrame({
        "일시":[tmEf],
        "최저기온":[tmn],
        "최고기온":[tmx],
        "날씨":[wf]
    })
    dfList.append(df)
weatherInfo = pd.concat(dfList)
weatherInfo

                  일시 최저기온 최고기온        날씨
0   2021-07-15 00:00   25   33      구름많음
0   2021-07-15 12:00   25   33      구름많음
0   2021-07-16 00:00   24   33      구름많음
0   2021-07-16 12:00   24   33  구름많고 소나기
0   2021-07-17 00:00   24   32      구름많음
..               ...  ...  ...       ...
0   2021-07-19 00:00   25   29      구름많음
0   2021-07-19 12:00   25   29  구름많고 소나기
0   2021-07-20 00:00   25   29        흐림
0   2021-07-21 00:00   25   29        흐림
0   2021-07-22 00:00   25   30        흐림

[533 rows x 4 columns]